### ISSUE TITLE
Create npm release for 2.2.1

### ISSUE THREAD

**Issue by peterennis** [edgarordonez/d3-stencil#113]
I want to look into react testing again and need a new release.

![Capture734](https://user-images.githubusercontent.com/140737/69456799-69997280-0d20-11ea-8d5e-9e008ef5ace2.PNG)
![Capture733](https://user-images.githubusercontent.com/140737/69456800-69997280-0d20-11ea-862e-7935403e0295.PNG)

**Comment by edgarordonez** [comment]
I'm working on it!

- New release after fix #117 and also it's gonna be cool to try if the automatic release using GitHub Actions is well set up.

**Comment by peterennis** [comment]
Nice!
Currently testing this: https://github.com/ionic-team/stencil-ds-plugins-demo
It looks to be the solution for Angular, React, and Vue (future) with Stencil.

I have a working component here: https://aeicons.adaept.com/
Integrated with Angular here: https://aetabs.adaept.com/tabs/about
using the 1.9.0-x Stencil release.

I will keep you in the loop with React once the Ionic-Team get their demo
working with Windows 10.
