### ISSUE TITLE
CI removal

### ISSUE THREAD

**Issue by peterennis** [edgarordonez/d3-stencil#115]
Is that related to https://github.com/edgarordonez/d3-stencil/issues/109 ?

**Comment by edgarordonez** [comment]
Hello @peterennis 

Yes! Actually, I switched to GitHub Actions a few days ago. I have to set up more complex workflows to avoid this kind of errors: #117

So, I guess that I'll be able to close #115 and #109 soon.

I'm moving to a new apartment... 📦and I'm kinda busy this week. :(

I'll back soon. (I wanna fix #117 ASAP setting `paths` into the `tsconfig.json`. I don't wanna have something broken in npm...)

Thanks for all!

**Comment by peterennis** [comment]
Happy Christmas in your New Apartment 🎄 🔔 🎅
