### ISSUE TITLE
Install and import d3-stencil and there is an issue

### ISSUE THREAD

**Issue by ChrisGrigg** [edgarordonez/d3-stencil#117]
Hi,

Great work on this library.

When I installed d3-stencil and import it:

`import 'd3-stencil';`

I get the following error:

> Typescript Error
Cannot find module '/Users/edgar/Projects/pet-projects/d3-stencil/src/interfaces/index'.
node_modules/d3-stencil/dist/types/components.d.ts

> 'updateGraphData': (graphData: Partial<{ pieChart: Partial<{ labelFormat: import("/Users/edgar/Projects/pet-projects/d3-stencil/src/interfaces/index").Formats;

etc etc

It would be really good to have more detailed documentation on how to get started with this too. At the moment it's unclear.

**Comment by edgarordonez** [comment]
Hello @ChrisGrigg 

I've just realized that I made a mistake in the last release. :(
I'm working to solve it ASAP. (Hopefully, I can finish it before this weekend).

My apologies 🙏  I have to increase the testing part to avoid those errors.

I'll fix it soon! 

Thanks for letting me know. :)

**Comment by thepian** [comment]
Is this release out?

**Comment by edgarordonez** [comment]
Closed because of the next release of v2.2.1 - Ready for Friday 27 Mar around 5 pm (CET/UTC+1 )

Thanks! 🚀📊
