### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by edgarordonez** [edgarordonez/d3-stencil#2]
I have some tests in the code but isn't enough.

For that and taking advantage that this month is [Hacktoberfest](hacktoberfest.digitalocean.com). 😄 
I purpose you to add some tests, not in all the code, be can move forward with the list or another thing if you have any suggestion.

We can start with:

- Check the `test/utils` that already exists and add more or improve those.
- Write a test for `shared/formats`.
- Write a test for `decorators/ resize`.
- Write tests for entire components `unit and e2e`.

**Comment by peterennis** [comment]
@edgarordonez 

I recommend closing this and creating a new one for D3-Stencil v2.0.0
based on this PR: https://github.com/edgarordonez/d3-stencil/pull/43
in connection to these test results.

![Capture577](https://user-images.githubusercontent.com/140737/59871554-b2ea2e00-934c-11e9-8bc3-8778faa8e561.png)
