### ISSUE TITLE
npm start shows blank page

### ISSUE THREAD

**Issue by peterennis** [edgarordonez/d3-stencil#26]
Windows 10, Chrome

![Capture203](https://user-images.githubusercontent.com/140737/57415482-3989e800-71b1-11e9-9016-41927e7f273d.png)

**Comment by peterennis** [comment]
![Capture205](https://user-images.githubusercontent.com/140737/57415876-9fc33a80-71b2-11e9-9425-44c79a95e1fd.png)

**Comment by edgarordonez** [comment]
Wow! 

Thank you so much @peterennis for these issues. I'll start with them this evening.

We are in touch! :)

**Comment by edgarordonez** [comment]
Hello @peterennis 

This problem should be solved with the version `1.0.2`. 🎉 

I'll invest more time next weekend to address other things and keep improving the code quality.

I'm gonna close this issue, feel free to add a new one for any trouble.

Thanks!! 🙏
