### ISSUE TITLE
Wardley maps

### ISSUE THREAD

**Issue by edgarordonez** [edgarordonez/d3-stencil#3]
Did you know about [Wardley maps](https://medium.com/wardleymaps)?

I've learned about those graphs or techniques in the last [BCN Craftmanship](http://scbcn.github.io/), and I found it very interesting, so I'd like to add some structure compatible with the `d3-stencil`  and add those graphs into the catalogue.

I think that we can create a new specific structure for that, for example, as I did in the BGC Matrix, I know that it's a big Issue, but feel free, no pressure, we haven't deadlines here.

We'll be in touch if you want to do this! :)

**Comment by peterennis** [comment]
@edgarordonez 
I read this and it is very interesting. I feel it is a long term possibility.

It is probably more beneficial to add integration examples based on selection from here:
https://github.com/d3/d3/wiki/Gallery

Integration of the component with Angular/React/Vue examples
e.g. I have these skeletons in process:

https://github.com/peterennis/aeicons-angular
https://github.com/peterennis/aeicons-react
https://github.com/peterennis/aeicons-vue

**Comment by edgarordonez** [comment]
Hey, yep it's really interesting! I've never used, but I have to.

Do you wanna have examples about how to use the components inside Angular, React, Vue? Ofc. 

Would be cool to have the Wardley maps, but I think after increase the tests, examples, etc. totally agree!

**Comment by peterennis** [comment]
I would like to put D3-Stencil as a component in my test apps and just have it work.
No/minimal changes to the component to make it work.
Documentation of the process and add details to the website.
This becomes a working example of Stencil integration for others to reference.
Write a Medium post?
Blog release?
Newsletter info for Ionic?
etc.
TBD

**Comment by edgarordonez** [comment]
Cool! 

I like this.
I'll create a new issue, something like a "Docs & Examples roadmap" to discuss these topics. 👍

I'm gonna close this. I have Wardley in mind for the future.
