### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by peterennis** [edgarordonez/d3-stencil#30]
![Capture215](https://user-images.githubusercontent.com/140737/57816400-05be3d80-7730-11e9-99ef-831713f49923.png)

![Capture218](https://user-images.githubusercontent.com/140737/57816419-18d10d80-7730-11e9-8e23-d84fe2f0e9d2.png)

![Capture220](https://user-images.githubusercontent.com/140737/57816442-2a1a1a00-7730-11e9-93ac-0cf5822651e7.png)

Then `npm audit fix --force`

![Capture221](https://user-images.githubusercontent.com/140737/57816448-30a89180-7730-11e9-8b31-0737679196eb.png)

**Comment by peterennis** [comment]
@edgarordonez 
The security issues are fixed via updating jest and puppeteer.
I pulled those updates out of the PR as I also saw the drop back from jest 24 to 23.
The plan is now to fix it in a new dev branch for Stencil One.

**Comment by edgarordonez** [comment]
Closed by https://github.com/edgarordonez/d3-stencil/pull/31
