### ISSUE TITLE
package-lock optional true

### ISSUE THREAD

**Issue by peterennis** [edgarordonez/d3-stencil#32]
This reference: https://stackoverflow.com/questions/54411377/package-lock-json-file-package-with-optional-true

![Capture542](https://user-images.githubusercontent.com/140737/57823944-39a85b80-774e-11e9-83a0-c21d88096d73.png)

This history: https://npm.community/t/package-lock-json-keeps-changing-between-platforms-and-runs/1129

This commit: https://github.com/peterennis/d3-stencil/commit/78795fff484de749bec3dc5a39b92a7552410376

I will update npm and see if it fixes the bouncing.

**Comment by peterennis** [comment]
```
C:\ae\d3-stencil>npm install npm@latest -g
C:\Users\peter\AppData\Roaming\npm\npx -> C:\Users\peter\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
C:\Users\peter\AppData\Roaming\npm\npm -> C:\Users\peter\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
+ npm@6.9.0
added 54 packages from 9 contributors, removed 15 packages and updated 47 packages in 17.297s

C:\ae\d3-stencil>npm --version
6.9.0

C:\ae\d3-stencil>
```

**Comment by peterennis** [comment]
Pull and build latest sec branch still shows optional true as a diff.

![Capture543](https://user-images.githubusercontent.com/140737/57824922-8b9eb080-7751-11e9-8417-1580208dd67f.png)

```
C:\ae\d3-stencil>node --version
v10.14.2

C:\ae\d3-stencil>
```

Try latest Node LTS next.

**Comment by peterennis** [comment]
![Capture544](https://user-images.githubusercontent.com/140737/57825409-a540f780-7753-11e9-97b3-2b082f255b11.png)

![Capture545](https://user-images.githubusercontent.com/140737/57825413-aa05ab80-7753-11e9-9fea-99091b9bb6c7.png)

Looks like this npm "feature" is still active for these versions.

**Comment by edgarordonez** [comment]
Can we close this? WDYT? 🤔

**Comment by peterennis** [comment]
There is some difference with package-lock.json after I pulled the merge commit.
I will test as follows:

1. delete package-lock.json
2. delete node_modules
3. npm i
4. npm start
5. See if there are differences

Newer versions of npm seem to be getting better at this.

If there are no changes in my test we can close the ticket.

If there are changes we will need to expend some more gray cells ☹️ thinking.

**Comment by peterennis** [comment]
I see the following after testing:

![Capture585](https://user-images.githubusercontent.com/140737/59959818-4e75be80-9473-11e9-8120-67e3f83e29c7.png)

![Capture586](https://user-images.githubusercontent.com/140737/59959819-546b9f80-9473-11e9-86ed-751d8c4f4137.png)

There is some change to package-lock and a clean merge PR is not possible.

**Comment by edgarordonez** [comment]
Yep... I see, and what about if I push these changes? 🤔

**Comment by peterennis** [comment]
Ok. Do it. Let me know and I will pull and test again.

**Comment by peterennis** [comment]
no longer seems to be an issue in newer version
