### ISSUE TITLE
Future development

### ISSUE THREAD

**Issue by peterennis** [edgarordonez/d3-stencil#35]
@edgarordonez 

This issue: https://github.com/ionic-team/stencil/issues/1535

If it is fixed then 0.18.1 seems to be a good place to
end the D3-Stencil version 1 line.

There are many breaking changes here:

https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md

Call this the D3-Stencil version 2? WDYT?

![Capture550](https://user-images.githubusercontent.com/140737/57901153-ab4cdc00-7818-11e9-9156-4b16bb6f6729.png)

**Comment by peterennis** [comment]
When the issue is fixed I can add Husky back in
per this commit:

https://github.com/edgarordonez/d3-stencil/pull/34/commits/30a5a31ada8d6c5d32bf50ca39cd11a4143b755d

**Comment by peterennis** [comment]
@edgarordonez 

FYI

https://github.com/ionic-team/stencil-component-starter/commit/7cc5f032cd8f57b8c51feb5c08b53883b24476bc

**Comment by peterennis** [comment]
@edgarordonez FYI https://github.com/rollup/rollup/issues/2865

**Comment by edgarordonez** [comment]
Hello @peterennis,

Thanks for your time. I'm a little bit busy, but I'll be more relaxed the next week. However, I'm gonna try to update d3-stencil tonight since both issues were closed. So, maybe we can try to update, right?

Keep in touch! 

Thanks! 🙏💪🏼

**Comment by peterennis** [comment]
@edgarordonez 
PR updated. This comment: https://github.com/edgarordonez/d3-stencil/pull/31#issuecomment-494098897
You can try to update. I recommend ignoring the CI coveralls if you get it to build and run.
However, I am curious to know what is blocking it.
