### ISSUE TITLE
Type 'Promise<void>' is not assignable to type 'void'.

### ISSUE THREAD

**Issue by peterennis** [edgarordonez/d3-stencil#38]
![Capture255](https://user-images.githubusercontent.com/140737/58046875-67e5bc80-7afb-11e9-8448-5277f89bc360.png)

Related: https://github.com/edgarordonez/d3-stencil/issues/36

Built at this commit: https://github.com/peterennis/d3-stencil/commit/870893593d487fbc55d698403f352ecfef43d2f7

**Comment by peterennis** [comment]
@edgarordonez 

Ref: https://github.com/microsoft/TypeScript/issues/12871 ???

![Capture257](https://user-images.githubusercontent.com/140737/58050071-35d85880-7b03-11e9-923c-1c1a5cb02e95.png)

Needs some ts fu :cry:

**Comment by peterennis** [comment]
Using some google fu

This commit: https://github.com/peterennis/d3-stencil/commit/313ccfb2b3c3ca1c26f3633abbf06a57d1e36312

**Comment by peterennis** [comment]
Test: Delete package-lock and node_module
`npm i`
`npm start`
Result:

![Capture552](https://user-images.githubusercontent.com/140737/58069070-be2d1c80-7b48-11e9-84ec-9132276d0785.png)

**Comment by peterennis** [comment]
@edgarordonez 
Use Ctrl-C to exit shows this:

![Capture553](https://user-images.githubusercontent.com/140737/58069126-ed438e00-7b48-11e9-92d5-a231f975f988.png)

I will open a ticket upstream with stencil.

```

[ ERROR ]  write EPIPE Error: write EPIPE at ChildProcess.target._send
           (internal/child_process.js:750:20) at ChildProcess.target.send
           (internal/child_process.js:634:19) at WorkerMain.stop
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65630:31)
           at WorkerManager.stopWorker
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65717:20)
           at WorkerManager.destroy
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65783:22)
           at addDestroy
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65906:32)
           at destroys.forEach.destroyFn
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65918:13)
           at Array.forEach (<anonymous>) at NodeSystem.destroy
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65917:23)
           at process.once
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\cli\index.js:403:24)


[ ERROR ]  write EPIPE Error: write EPIPE at ChildProcess.target._send
           (internal/child_process.js:750:20) at ChildProcess.target.send
           (internal/child_process.js:634:19) at WorkerMain.stop
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65630:31)
           at WorkerManager.stopWorker
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65717:20)
           at WorkerManager.destroy
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65783:22)
           at addDestroy
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65906:32)
           at destroys.forEach.destroyFn
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65918:13)
           at Array.forEach (<anonymous>) at NodeSystem.destroy
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\sys\node\index.js:65917:23)
           at process.once
           (C:\ae\adaept.com\d3-stencil\node_modules\@stencil\core\dist\cli\index.js:403:24)

Terminate batch job (Y/N)?
```

**Comment by simonhaenisch** [comment]
This is not a bug but a Typescript feature. `this.tooltipEl.hide()` returns a promise, but you're telling your code that `toHide` expects a function that returns void... Not sure why you type it as `void` in the first place (since it can infer the type for you), but if you want to do that, you have to change your code to either

```ts
const toHide = async (): Promise<void> => this.tooltipEl.hide();
```

or 

```ts
const toHide = async () => this.tooltipEl.hide();
```

(you can leave out the `async` keyword but if it returns a promise, it should be marked as async)

Maybe have a look at the "function types" section of https://www.typescriptlang.org/docs/handbook/functions.html, if you're unfamiliar with them.

**Comment by peterennis** [comment]
@edgarordonez 
Fixed here: https://github.com/peterennis/d3-stencil/blob/fab55769c9e7090f93f863b3c010c6a05b0a4eb6/src/components/line-chart/line-chart.tsx#L72
(I think...)

@simonhaenisch Thanks for the tip and guide 👍
