### ISSUE TITLE
General code review

### ISSUE THREAD

**Issue by edgarordonez** [edgarordonez/d3-stencil#4]
I did this library all alone in my journeys home/office, so it would be a pleasure if you want to share your opinion with me and do a code review about the structure or another part.

We can refactor any part of the code or get rid off if you think that it is horrible.

**Comment by peterennis** [comment]
@edgarordonez 

Fixed in this PR: https://github.com/edgarordonez/d3-stencil/pull/43

I recommend to close this issue and make a new one that includes
planning for D3-Stencil v2.0.0 future and website development.
